# Generated by Django 5.0.3 on 2024-03-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='время')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('action', models.CharField(max_length=100, verbose_name='действие')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='вознаграждение')),
                ('periodicity', models.PositiveIntegerField(verbose_name='периодичность')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('duration_time', models.TimeField(verbose_name='продолжительность')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='дата следующего действия')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
        migrations.CreateModel(
            name='NiceHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='место')),
                ('action', models.CharField(max_length=100, verbose_name='действие')),
            ],
            options={
                'verbose_name': 'Приятная привычка',
                'verbose_name_plural': 'Приятные привычки',
            },
        ),
    ]
